import os
import httpx
import asyncio

API_URL = "https://scribes-version-20-production.up.railway.app"

async def main():
    async with httpx.AsyncClient() as client:
        # 1. Register test user
        register_data = {
            "email": "testagent@example.com",
            "password": "password123",
            "handle": "testagent",
            "name": "Test Agent"
        }
        res = await client.post(f"{API_URL}/auth/register", json=register_data)
        if res.status_code not in (200, 201):
            if "duplicate" not in res.text.lower() and "exists" not in res.text.lower():
                print("Register failed:", res.text)
        
        # 2. Login
        login_data = {
            "email": "testagent@example.com",
            "password": "password123"
        }
        res = await client.post(f"{API_URL}/auth/login", json=login_data)
        if res.status_code != 200:
            print("Login failed:", res.text)
            return
            
        token = res.json().get('token')
        print("Got token")
        
        # 3. Create a post
        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }
        post_data = {
            "content": {
                "title": "Agent Test Post",
                "body": "This is a post generated by the AI agent to test the feed."
            },
            "visibility": "public"
        }
        res = await client.post(f"{API_URL}/posts", json=post_data, headers=headers)
        print("Post creation response:", res.status_code, res.text)

asyncio.run(main())
